"""third migration

Revision ID: cd2cea7225f7
Revises: aee88dd3c848
Create Date: 2020-07-23 11:32:58.668221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2cea7225f7'
down_revision = 'aee88dd3c848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_url')
    op.drop_column('recipes', 'image_filename')
    # ### end Alembic commands ###
